### ISSUE TITLE
Hey Mihir

### ISSUE THREAD

**Issue by piterat** [KarandikarMihir/website#14]
Hey I am trying to reach you, I notice you post a lot on stackoverflow regarding react. I have a very specific question i could use your help with, if your willing.
https://stackoverflow.com/questions/65081893/asce-hazard-tools-filling-form-with-javascript-information-comes-in-as-nodelis
thanks for your time,
Thomas Pitera

**Comment by KarandikarMihir** [comment]
@piterat Hey! Sorry I'm seeing your message just now. The link does not seem to be working anymore. I hope your problem was resolved. Closing this issue.
